version: '3.2'
services:
    php:
        build: ./php
        image: php
        container_name: php
        expose:
            - "9000"
        ports:
            - "7272:7272" #workman聊天室
            - "55151:55151" #workman聊天室
        volumes:
            - ../../www:/data/www:rw
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
            - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ../logs/php:/var/log/php-fpm:rw
        restart: always
        command: php-fpm
        extra_hosts:
          - "api.sas.test:192.168.66.75"
          - "api.bmp.test:192.168.66.75"
          - "api.mam.test:192.168.66.75"

    nginx:
        build: ./nginx
        image: nginx
        container_name: nginx
        links:
            - php:php
        volumes:
            - ../../www:/data/www:rw
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/certs/:/etc/nginx/certs
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../logs/nginx:/var/log/nginx
        ports:
            - "80:80" #宿主端口：容器端口
        restart: always
        depends_on:
            - php
        command: nginx -g 'daemon off;'

    mysql:
        build: 
            context:
                ./mysql
            args:
                - "--ignore-db-dir=lost+found"
        image: mysql
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ../data/mysql:/var/lib/mysql:rw
            - ../logs/mysql:/var/lib/mysql-logs:rw
            - ./mysql/my.cnf:/etc/my.cnf:ro
            - ../logs/mysql-files:/var/lib/mysql-files/
        environment:
            MYSQL_ROOT_PASSWORD: root    
        restart: always
        depends_on:
            - php
        command:
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --lower_case_table_names=1
            --innodb_use_native_aio=0
        security_opt:
            - seccomp:unconfined    

    redis:
        build: ./redis
        image: redis
        container_name: redis
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ../data/redis:/data
        restart: always
        depends_on:
            - php

    python:
        build: ./python
        image: python
        container_name: python
        volumes:
            - ../../pythonCode:/usr/src/app:rw
            - ../logs/scrapyd:/usr/src/app/scrapyd/logs:rw
        ports:
            # - '81:81'
            - '6800:6800' #scrapyd
            - '8000:8000' #gerapy
            - '3000:3000' #gerapy
            - '5000:5000'
        restart: always
        stdin_open: true
        tty: true
        links:
            - mysql
            - redis

    beanstalk:
        build: ./beanstalk
        image: beanstalk
        container_name: beanstalk
        ports:
            - "11300:11300"
        privileged: true
        depends_on:
            - php   

    golang:
        build: ./golang
        image: golang
        container_name: golang
        ports:
            - "8088:8088"
        links:
            - mysql
            - redis
        volumes:
            - ../../goCode:/go
        tty: true
        
    # elasticsearch:
    #     build: ./elasticsearch
    #     image: elasticsearch
    #     container_name: elasticsearch
    #     volumes:
    #         - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    #         - ../data/elasticsearch:/usr/share/elasticsearch/data:rw
    #     environment:
    #         - cluster.name=docker-cluster
    #         - bootstrap.memory_lock=true
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #     ports:
    #         - "9200:9200"
    #     depends_on:
    #         - php

    # elasticsearch-head:
    #     image: mobz/elasticsearch-head:5
    #     container_name: elasticsearch-head
    #     ports:
    #         - "9100:9100"
    #     depends_on:
    #       - elasticsearch

    # logstash:
    #     build: ./logstash
    #     image: logstash
    #     container_name: logstash
    #     volumes:
    #         - ./logstash/templates:/usr/share/logstash/templates:ro
    #         - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    #         - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    #     ports:
    #         - "5000:5000"
    #         - "9600:9600"
    #     environment:
    #         LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    #     depends_on:
    #         - elasticsearch 

    # nextcloud:
    #     build: ./nextcloud
    #     image: nextcloud
    #     container_name: nextcloud
    #     volumes:
    #         - ../data/nextcloud:/var/www/html/data:rw
    #         - ../../www/nextcloud:/var/www/html:rw
    #     ports:
    #         - 9700:80
    #     links:
    #         - mysql

    # collabora:
    #     build: ./collabora
    #     container_name: collabora
    #     ports:
    #         - 9701:9980
    #     environment:
    #         - domain=pan\\.bjadks\\.com
    #         - username=admin
    #         - password=111111
    #         - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    #     restart: always
    #     cap_add:
    #         - MKNOD

    # splash:
    #     image: scrapinghub/splash
    #     container_name: splash
    #     ports:
    #         - "8050:8050"
    #         - "5023:5023"
    #     restart: always

    #https://github.com/jhao104/proxy_pool
    #Workdir proxy_pool
    #docker build -t proxy_pool .
    # proxy_pool:
    #     image: jhao104/proxy_pool
    #     container_name: proxy_pool
    #     ports:
    #         - "5010:5010"
    #     links:
    #         - redis
    #     environment:
    #         DB_CONN: "redis://:111111@redis:6379/0"

    anyproxy:
        build: ./anyproxy
        image: anyproxy
        container_name: anyproxy
        volumes:
            - ../logs/anyproxy:/app/log:rw
        restart: always
        stdin_open: true
        tty: true    
        ports:
            - "8001:8001"
            - "8002:8002"
